language: node_js
node_js:
  - '6'

#########################
## Setup
#########################
sudo: false
cache:
  directories:
    - node_modules

before_script:
  - npm prune

after_success:
  - npm run coverage
  - npm run semantic-release
  - npm run reparo

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
